name: 'Notification for pending release'
description: 'Create an issue if there is a release pending'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  days-to-ignore:
    description: 'Unreleased commits older than the no. of days mentioned in this setting shall be reported'
    required: true
    default: 7
runs:
  using: 'node14'
  main: 'dist/index.js'
